name: security audit

on:
  push:
  pull_request:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 10.11.0
      - name: Root audit
        run: |
          pnpm install --frozen-lockfile
          pnpm audit
      - name: BackEnd audit
        working-directory: backEnd
        run: |
          pnpm install --frozen-lockfile
          pnpm audit
      - name: FrontEnd audit
        working-directory: frontEnd
        run: |
          pnpm install --frozen-lockfile
          pnpm audit